liatrio/devops-bootcamp

docs/4/4.4-maven-integration.md

configure jenkins twice, once to build jobs not only wiht git polling and again but with a webhook

Added another part to step 4 of section 4.4

---

docs/1/1.4-external-resources.md

YOW! Nights March 2016 Martin Fowler - Infrastructure As Code

Update 1.4 External Resources

---

docs/index.html

Adds the script for the search plugin for issue; issue is fixed

---

docs/5/5.0-overview.md

Created some basic goals for the Chapter. If anything could be added or changed please comment.

DOB-629 Wrote some Chapter Goals for the 5.0 Overview page

---

docs/5/5.4-tomcat.md

DOB-633 Adding Section 4

---

docs/5/5.2-security.md

Combines 5.2 and 5.4 Into one longer section as DOB-631 asks for.

Combines the old 5.2 and 5.4

---

docs/6/6.5-auto-scaling.md
docs/7/7.1-configuration-managers.md
docs/7/7.2-chef.md
docs/7/7.3-terraform.md

Adds consultant sections to 6.5  & 7.1-.3 DOB-769

Adds consultant sections to 6.5  & 7.1-.3

---

docs/6/6.2-aws.md

- update billing costs explanation
- add tagging
- add console vs cli

Dob 754 update aws introduction

---

docs/6/6.3-s3-cloudfront.md

This PR adds clarification to cleaning up CloudFront Distributions on AWS. Additionally, a deliverable has been added to have users consider the implications of resource wait times in automation.

Added step and deliverable to cleanup section

---

docs/6/6.7-ecs.md
docs/_sidebar.md

Adds Chapter 6 Section 7 on ECS and microservices.

Chico 884 Bootcamp ECS

---

docs/4/4.3-maven-integration.md
docs/4/4.6-npm.md

Ch4 changes

---

docs/contributors.md

I added my name to the list of contributors.

Added my name to the contributors

---

docs/contributors.md

Simply added my name and a link to my GitHub profile on the contributors page

Add my name to the contributors list

---

docs/6/6.8-eks.md

Updated with new information on Sockshop and EKS Node creation

Updated instructions for EKS exercise

---

docs/1-introduction/basics-vim.md

Spelling correction for basics-vim.md

---

docs/7/7.2-chef.md

Update deprecated terms (ChefDK and Rubocop) and split exercise into two

Update Chef Exercise

---

docs/2-virtual-machines-containers/container-management.md

Changed:
1. "much also be managed" to "must also be managed"
2. "wether" to "whether"

Spelling corrections for container-management.md

---

docs/7/7.3-terraform.md
docs/7/7.4-ansible.md

- Changed the interpolation section due to deprecations
- Fixed some typos in the ansible section

Update Terraform section

---

docs/2-virtual-machines-containers/2.2-local-development.md
docs/3-cloud-computing/3.2.1-s3-cloudfront.md
docs/3-cloud-computing/3.3.3-vmss.md
docs/3-cloud-computing/3.3.4-az-packer.md
docs/3-cloud-computing/3.3.6-aks.md

Fixed broken links, spelling errors, wrong section numbers, and step numbers in chapter 2 and 3.

Fix Links/Spelling/Numbering

---

docs/index.html

- add bootcamp to github pages

fix: add bootcamp to github pages

---

docs/3-cloud-computing/3.2.5-ecs.md
docs/3-cloud-computing/3.3.6-aks.md
docs/4-software-development-practices/4.1.4-stories.md
docs/4-software-development-practices/4.2-jira.md
docs/4-software-development-practices/4.3.2-git.md
docs/4-software-development-practices/4.5.2-functional-testing.md

Updated the manifest to be more update to date with the current version of Kubernetes

small change to manifest for 3.3.6

---

docs/3-cloud-computing/3.2.5-ecs.md
docs/3-cloud-computing/3.3.6-aks.md
docs/4-software-development-practices/4.1.4-stories.md
docs/4-software-development-practices/4.2-jira.md
docs/4-software-development-practices/4.3.2-git.md
docs/4-software-development-practices/4.5.2-functional-testing.md
docs/5-release-management/5.2-declarative-pipelines.md
docs/5-release-management/5.3-build-tools.md
docs/5-release-management/5.3.2-maven-integration.md
docs/5-release-management/5.4.2-helm.md

Very small changes for a couple sections from chapter 3 and 5

Bengal changes

---

7-kubernetes-container-orchestration/7.7-k8sthw.md

All hyperlinks were rerouting to the home page. This was due to the links being wrapped with quotations.

fix: issue with hyperlinks not working

---

1-introduction/1.2-liatrio-and-devops.md

Fixing grammar error in item 1.2 liatrio and devops - The goal number 1 section, adding 'to'

Merge bugfix/1-2-grammar-error-fix

---

2-virtual-machines-containers/2.1-golden-images.md

Changed the Spelling of "Excersize" to "Exercise"

Updated 2.1-golden-images.md

---

.github/workflows/blank.yml

Added Linter For Markdown 

---

3-cloud-computing/3.2.7-eks.md

docs: Adds some clarifying hints to the EKS section.

---

4-software-development-practices/4.1-overview.md

The 4.1 overview of the boot camp seemed to be lacking some detail. I thought it could use a little more elaboration on some of the terms used. This should help the apprentices have a better image in their heads when they approach the respective section.
Resources: 
* https://www.planview.com/resources/guide/what-is-agile-program-management/agile-frameworks/
* https://aws.amazon.com/what-is/sdlc/#:~:text=The%20software%20development%20lifecycle%20(SDLC,expectations%20during%20production%20and%20beyond.

Nick 4.1 update

---

.cspell.json
docs/3-cloud-computing/3.3.5-aci.md

Adds hint in ACI section to mention the architecture of your container.

---

docs/6-infrastructure-configuration-management/6.2-ansible.md
docs/README.md

replace install of Jenkins instruction to install GitHub self hosted runner instruction for all exercises in the Ansible chapter

Ansible jenkins to gh runner

---

docs/_stats.md
src/docksify-plugins/generate-chart.js
src/docksify-plugins/read-metadata.js

Adds chapter and bootcamp total hours and weeks generated off the metadata
reworked how bootcamp metadata is fetched so we dont have out of date caching

checkpoint: scaffolding added but not async

---

docs/8-kubernetes-container-orchestration/8.6-webhooks.md
examples/ch8/webhooks/test-pods/test1.yaml
examples/ch8/webhooks/test-pods/test2.yaml
examples/ch8/webhooks/test-pods/test3.yaml
examples/ch8/webhooks/test-pods/test4.yaml
examples/ch8/webhooks/test-pods/test5.yaml
examples/ch8/webhooks/test-pods/test6.yaml
examples/ch8/webhooks/test-pods/test7.yaml

- Section namespace and container tag were changed to "myapp" since "busybox" is a popular image that is used in lots of docker applications
- Section added more hints to help with flow
- Section updated test files to reflect previous changes

Modified Section 8.6 of the DOB

---

docs/4-cloud-computing/4.2.7-eks.md

Added hint after step 5 of exercise 1

4.2.7 Exercise 1 hint

---

docs/8-kubernetes-container-orchestration/8.6-webhooks.md

- Spell check and some minor changes to deliverables

Fixed some minor issues with section 8.6

---

docs/4-cloud-computing/4.2.6-ecs.md

Closes #271 (Note that the issue specifies section 3.2.6, but chapter 3 has since been refactored to chapter 4)

Removed broken exercise from section 4.2.6. Closes #271

---

docs/4-cloud-computing/4.3.1-storage-accounts.md

This update is to get the azure section on the same level as the AWS section.
- Removed most of the hand holding code snippets.
- Added Deliverables

Updated Storage Account Section #374 #375

---

docs/4-cloud-computing/4.3.6-aks.md

- Added Deliverables to be discussed
- Updated the code to encourage learning

Updated Section 4.3.6 with new deliverables and notes #374 #375

---

docs/4-cloud-computing/4.3.6-aks.md
docs/6-release-management/6.2.4-npm.md

- Fixed the practice application to use Express JS
- Added documentation for Eslint and Express JS

Updated Section 6.2.4 NPM #350

---

docs/4-cloud-computing/4.3.6-aks.md

Spacing was a bit too close for the steps in this section. It is more spaced out and no longer feels congested.

Fixed Spacing for Section 4.3.6

---

docs/6-release-management/6.2.5-go-releaser.md

Added hint to Go Releaser exercise

---

.cspell.json
docs/7-infrastructure-configuration-management/7.1.4-terraform-providers.md
docs/README.md
src/quizzes/chapter-7/section-4/api-checkpoint.js

Most of the content has stayed the same, but has been reordered and summarized.

Overhall the Terraform Provider Section (7.1.4)

---

docs/1-introduction/1.2-liatrio-and-devops.md
docs/README.md
src/quizzes/landing-page-quiz.js

Adds a sample quiz to the landing page, and updates the chapter list in the `Learning Goals` section. It hadn't been updated since before the GitHub chapter was added.

Landing page update

---

docs/1-introduction/1.3.1-unix.md
src/quizzes/chapter-1/1.3.1/unix-quiz.js

Added basic Unix quiz to the end of the section. Feels silly making a quiz this easy, but the section covers these commands in detail so it does seem fitting.

Added Unix quiz

---

docs/1-introduction/1.3.5-networking.md
src/quizzes/chapter-1/1.3.5/subnets-quiz.js

Tests basic knowledge of `/8`, `/16`, and `/24` subnet masks

Added quiz about network addresses and subnets

---

docs/2-Github/2.0-overview.md
docs/2-Github/2.1-features.md
docs/2-Github/2.2-Actions.md
src/quizzes/chapter-2/2.2/advanced-workflow-quiz.js
src/quizzes/chapter-2/2.2/basic-workflow-quiz.js

1. Added a quiz after each exercise in the section
- The first focuses on basics and includes secrets, triggers, and matrices
- The second is more advanced and includes composite actions, reusable workflows, self-hosted runners and upload/download artifact
2. Fixed a few spelling/grammar errors from 2.0-2.2

Added 2 quizzes about workflows

---

docs/1-introduction/1.1-devops-defined.md
docs/1-introduction/1.2-liatrio-and-devops.md
docs/1-introduction/1.3.1-unix.md
docs/1-introduction/1.3.2-vim.md
docs/1-introduction/1.3.3-installations.md
docs/1-introduction/1.3.4-passwords-and-keys.md
docs/1-introduction/1.3.5-networking.md
docs/1-introduction/1.4-external-resources.md
docs/README.md

- In chapter 2 I started adding a "Knowledge Check" header to the quizzes, so I went back through chapter 1 and added those headers to all the previous quizzes
- I also noticed that there were some inconsistencies with the Deliverables style, so I made them uniform with the rest of the bootcamp

Added headers to quizzes and formatted deliverables to be uniform

---

docs/1-introduction/1.3.4-passwords-and-keys.md
src/quizzes/chapter-1/1.3.4/sshconfig-quiz.js

Tests knowledge of Unix file permissions and basic reasoning behind ssh key exchanges

Added quiz about ssh and permissions

---

docs/3-virtual-machines-containers/3.1-golden-images.md
src/quizzes/chapter-3/3.1/immutable-infra-and-packer-quiz.js

Added quiz and slightly reformatted the markdown for the section to match the rest of the bootcamp

Added quiz about golden images, Packer, and immutable infra

---

docs/1-introduction/1.3.1-unix.md
docs/1-introduction/1.3.2-vim.md
docs/1-introduction/1.3.3-installations.md
src/quizzes/chapter-1/1.3.1/unix-quiz.js

Added the q! command to the list of vim commands, and edited the brew install command to use "cask" properly to work on Mac OS

vim instruction addition & brew cast fix

---

docs/3-virtual-machines-containers/3.2-local-development.md
src/quizzes/chapter-3/3.2/vagrant-quiz.js

Only 2 questions this time around. The second one is pretty simple, but is a great one for revisiting just to keep tool definitions dusted off. Minor grammar fixes to the markdown.

Added quiz about Vagrant and Packer

---

docs/4-cloud-computing/4.1-cloud.md
docs/4-cloud-computing/4.1.1-aws.md
src/quizzes/chapter-4/4.1.1/aws-quiz.js

- 3 question quiz that tests the user's understanding of tagging best practices and ensures they can properly execute commands using AWS CLI and aws-vault by asking what the outcome of running a specific command is
- Fixed deprecated link
- Slightly reformatted markdown to be consistent with rest of bootcamp

Added quiz to 4.1.1 about AWS CLI and tags

---

src/quizzes/chapter-4/4.1.1/aws-quiz.js

There was a backtic that was not escaped breaking the quiz

Fixes broken quiz for 4.1.1

---

docs/4-cloud-computing/4.0-overview.md
docs/4-cloud-computing/4.0.1-Cloud-Ecosystems.md
src/quizzes/chapter-4/4.0.1/service-ecosystems-quiz.js

Rather silly quiz, but gets the user to think about service ecosystems in real-world examples.
Slightly updated service offerings lists on 4.0.1

Added quiz to 4.0.1 about service ecosystems

---

docs/2-Github/2.2-Actions.md

Revert "Changed the echo command in sample workflow to be 'hello worl…d' instead of 'password'. Why would you echo your password"
This reverts commit b200d0daf073c6a9c2f51dd107b7d0d589e0bc2e.

Revert PR 443

---

docs/3-virtual-machines-containers/3.4-containers.md
src/quizzes/chapter-3/3.4/containers-quiz.js
src/quizzes/chapter-3/3.4/docker-quiz.js
src/quizzes/chapter-3/3.4/docker-self-hosted-runner-quiz.js

- Added the first quiz just below the container introduction and before Docker, so it focuses on the differences between containers and VMs
- Added second quiz just below Docker, before the exercises, and highlights some niche Docker concepts
- Added third quiz below the exercises that highlights the unique issue that arises in the exercises which stems from not having a volume attached. My goal for this quiz is to get them to consciously realize what the issue is why it happens. My hope is that this will immediately add value to the next section which covers compose and volumes

Added 3 quizzes to 3.4 about containers and Docker

---

docs/3-virtual-machines-containers/3.5.1-docker-compose.md
src/quizzes/chapter-3/3.5.1/docker-compose-quiz.js

Tests basic understanding of how Docker Compose aids you in managing containers

Added quiz to 3.5.1 about Docker Compose

---

docs/3-virtual-machines-containers/3.5.2-kubernetes.md
src/quizzes/chapter-3/3.5.2/k8s-quiz.js

- Reordered the sections contents to flow a bit better than before
- Added a simple quiz that tests basic knowledge of certain k8s resources and the differences between k8s and Docker Compose
- More questions could definitely be made for this quiz, but I feel like we can go much deeper later on in Chapter 8

Added quiz to 3.5.2 about Kubernetes

---

docs/4-cloud-computing/4.2.2-ec2.md
src/quizzes/chapter-4/4.2.2/ec2-and-jenkins-quiz.js

- Adds quiz to section 4.2.2 that covers some different areas of EC2 and Jenkins

Added quiz on EC2 and Jenkins

---

docs/4-cloud-computing/4.2.1-s3-cloudfront.md
src/quizzes/chapter-4/4.2.1/cloudfront-quiz.js
src/quizzes/chapter-4/4.2.1/s3-quiz.js

- Added a 7 question quiz that covers most things S3 (use cases, security, data durability, different storage class types)
- Added a 2 question quiz about CloudFront (question on use case and a question on CLI command knowledge)
- Removed consultant deliverables and added deliverable talking point

Added 2 quizzes about S3 and CloudFront

---

docs/3-virtual-machines-containers/3.4-containers.md

steps 8 and on incorrectly referred to script created on step 7 (not step 5).

aligns step ref to step number

---

docs/4-cloud-computing/4.1.1-aws.md
docs/4-cloud-computing/4.2.1-s3-cloudfront.md

Bootcamp section 4.2.1, exercise 1, step 12 currently instructs users to look for "Static web hosting" under the "Policy" tab.  Updated to "Properties" tab.

Update static web hosting tab

---

docs/9-platform-engineering/9.1-backstage.md
docs/README.md
docs/_sidebar.md

- Includes creating a GitHub Org to work with
- Standing up local instance of Backstage
- Basic customization of UI of Backstage
- Adding GitHub as an Authentication Provider and as the Sign-In service

Adds the start of the Backstage section of the PE chapter.

---

docs/9-platform-engineering/9.1-backstage.md

There were some steps in the backstage 'getting started' docs that we are skipping. Also fixed a typo

Updates Backstage auth to exercise

---

docs/6-release-management/6.2.5-go-releaser.md
docs/README.md

fix: Removed self-hosted runner requirement from 6.2.5

---

.cspell.json
README.md
docs/8-kubernetes-container-orchestration/8.8-hello-k8s.md
docs/README.md

-  adds  tip to use the the kubebuilder deploy image plugin for the hello-k8s project

docs: updates instructions for hello k8s project

---

docs/5-software-development-practices/5.6-hello-devops.md

fix: no more jira

---

docs/7-infrastructure-configuration-management/7.1.4-terraform-providers.md

The scaffolding no longer has those problematic lines by default (or so it seems)

fix: removed step from 3 from 7.1.4 Exercise 1

---

docs/9-platform-engineering/9.1.3-software-templates.md

Another link updated to the less sucky documentation

fix: the (old) docs are dead, long live the (new) docs

---

docs/3-AI-Engineering/3.1.2-ai-agents.md

Basically trying to instill HuddleChamp learning into a more generic phrasing. Definitely might need tweaking.

fix: sligthtly addede to Agent best practices

---

docs/2-Github/2.5-Security.md

fix: update example repo with one that has known vulnerabilities.

---

docs/5-cloud-computing/5.2.6-ecs.md

Removed wordage about seeing the dsk-ui application before

Updated a link, modified wordage

---

docs/5-cloud-computing/5.2.3-auto-scaling.md

fix: nitpick chapter numbering
