liatrio/devops-bootcamp

docs/5/5.2-jenkins.md, docs/5/5.3-tomcat.md, docs/5/5.4-nexus.md
Makes some formatting changes, as well as rewriting the exercise. Apprentices are now asked to set up multiple Jenkins jobs, instead of it being optional. Extended exercise options are included however, which are deploying within a single Jenkins job and deploying using a Maven plugin.
=> Updates Chapter 5 Section 3, Tomcat

docs/index.html
Adds next and previous page buttons to the bootcamp, using [docsify-pagination plugin.](https://github.com/imyelo/docsify-pagination)
=> DOB 797 Add 'Previous' and 'Next' page buttons

docs/index.html
Previously, when a new section is loaded the scrollbar isn't reset to the top of the page. 
This PR corrects that issue.
=> Resets scrollbar to top of page on load

docs/1-introduction/basics-installations.md, docs/1-introduction/basics-passwords-and-keys.md
Red Hat Enterprise Linux (RHEL) instead of REHL
=> fix Red Hat abbreviation, update ssh information

docs/4/build-tools_make.md, docs/_sidebar.md
- Adds a basic Make section to 4.3 Build Tools
- Highlights `make` basics
- Provides example Makefile
- Links to more complex Makefile for farther study
- Fixes Subsection numbers to 4.3.x for npm and GoReleaser
=> Add Initial Make Section

docs/1-introduction/devops-defined.md
The previous link to the Chef Blog article "What Devops Means to Me" was dead.
=> Fixed link to article "What Devops Means to Me"

docs/1-introduction/1.4-external-resources.md
Altered the links for Spotify Engineering Culture - Part 1 & 2 videos.
Part 2's link was private and no longer viewable.
Part 1's link was changed to match the same YouTube account of Part 2.
Added links to "Release It" and "Lean Enterprise" since both did not currently have links.
=> Pycast link fix

2-virtual-machines-containers/2.5.1-docker-compose.md
- There was an issue with an icon not displaying in an important section.
- Update that section (2.5.1) with details about Docker Desktop not supporting Compose V1 in June.
=> fixed 'important icon' and updated 2.5.1

3-cloud-computing/3.2.1-s3-cloudfront.md
The main change here is from the previously linked (and rather bloated) internal repo devops-knowledge-share-ui. For a lesson on hosting a static website first it did not work and additionally it was overly complex leading to confusion. This branch also addressed some typos and poor assumptions that the previous steps made. This branch also updates the S3 bucket permissions away from ACL rules (deprecated) and to Bucket Policies.
=> docs: Updates steps and repo in 3.2.1 so things work.

README.md
fixes alt syntax for liatrio image in `README.md`
=> fix: fixes alt syntax for liatrio image in README.md.

docs/4-software-development-practices/4.3.2-git.md
Fixing pathing in regards to how docsify interprets the image path for section 4.3.2
=> fixing image pathing regarding docsify

.cspell.json, docs/4-software-development-practices/4.5.5-test-automation.md, docs/README.md
As the title says.  It also enhances the exercises a bit and links them up with the upcoming GitHub chapter
=> 4.5.5 - Remove Jenkins and replace with GitHub Actions

.github/workflows/test-front-matter.yml, .husky/front-matter-condenser.js, .husky/pre-commit, docs/README.md, package-lock.json, package.json
Previous version of the front matter condenser looked at stated git changes. This worked for simple cases such as adding sections or updating existing sections but it did not handle removing sections from the bootcamp, renaming sections in the bootcamp. And it also did not offer an easy way to refresh the master record if it get messed with. The new approach uses the `_sidebar.md` file as the source of truth. This file drives the sidebar links on the bootcamp website and is effectively a list of all the sections that a camper would do. Each commit will now aggregate all front matter in sections found in the side bar (addendum excluded) and compare the aggregated list with the master record. Additionally this pr adds a workflow that simply compares the master record with all the sections …
=> Rework front matter condenser

docs/5-release-management/5.3.2-maven-integration.md, docs/README.md
replace Maven Jenkins build/deploy instructions with GitHub Actions instructions
=> Maven jenkins to GitHub

docs/4-cloud-computing/4.2.5-lambda.md
Bootcamp references describe_instance_status() to find the launch-time field-- this field is not accessable through describe_instance_status() but is in describe_instances().
=> Correcting incorrect function hint

docs/8-kubernetes-container-orchestration/8.2-volumes.md, examples/ch8/volumes/random-num-pod.yaml
Kubernetes requires lower case for the metadata name. I changed the example code in the examples folder and on the page that displays the contents of the file.
=> fixed syntax error (myPod -> my-pod)

docs/8-kubernetes-container-orchestration/8.5-hpas.md
`v2beta2` is deprecated and needed to be changed to `v2` instead.
=> Modified section 8.5 to use `v2` instead of `v2beta2`

docs/6-release-management/6.2.4-npm.md
The existing video link is set to private. I found a new video (15 min) and goes over the basics of NPM, how to use it, what it's used for, and a bit about semantic versioning.
old link: https://www.youtube.com/watch?v=x03fjb2VlGY
new ling: https://www.youtube.com/watch?v=P3aKRdUyr0s
=> added new link to NPM introduction

docs/4-cloud-computing/4.3.3-vmss.md, docs/README.md
Updating this section to be in line with the AWS section. 
- Removed most of the handholding code.
- Added deliverables
Deliverables:
- What is the purpose of Azure Virtual Machine Scale Sets (VMSS)?
Purpose: Is to show how similar it is to AWS's Auto Scaling Groups. 
Answer: VMSS is used to configure, manage, and update identical virtual machines. 
- Explain the difference between scaling out and scaling in within the context of VMSS.
Purpose: Early introduction to horizontal scaling. Good to have this in your mind when you get to the Kubernetes section.
Answer: Scaling out (horizontal scaling) is where you add more virtual machines. Scaling in is where you reduce the number of virtual machines in your scale set.
- Discuss how VMSS would be used in a real-world scenario, such as a …
=> Update az vmscalesets

docs/6-release-management/6.3.2-helm.md, examples/ch6/helm/DKS/templates/NOTES.txt
Updated the exercise 3 in Helm section to challenge apprentices to properly reference the backend service from the frontend. Added a challenge and hint to the exercise that suggests they can accomplish the exercise by only port-forwarding a single service. Small change to the Notes.txt in the Helm Example to display the correct ports.
=> Rephrased Helm exercise 3

.cspell.json, docs/7-infrastructure-configuration-management/7.2-ansible.md, docs/README.md, docs/contributors.md
Closes #401 by adding an exercise and blurb to the Ansible section regarding idempotency.
=> Ansible idempotency 

docs/1-introduction/1.2-liatrio-and-devops.md, src/quizzes/chapter-1/1.2/liatrio-tao-quiz.js
Added a few simple, reinforcing questions about the Liatrio Tao
=> Added Liatrio Tao quiz

docs/2-Github/2.4-APIs.md, src/quizzes/chapter-2/2.4/api-quiz.js
- Added a quiz to section 2.4 that tests the understanding of some of the differences between REST and GraphQL
- Threw one "gotcha" in there in the form of question 2. The answer seems like it would be GraphQL because it can query for exactly what it wants, but REST actually has a dedicated endpoint for exactly what the prompt is talking about.
- Changed a sentence in the section as it broke the 4th wall and didn't read like the rest of the bootcamp
#394
=> Added quiz about GitHub APIs #394

docs/2-Github/2.5-Security.md, src/quizzes/chapter-2/2.5/security-quiz.js
#394  
- Added a simple quiz that tests the differences between dependabot, code scanning, and secret scanning
- Added some text to the beginning of the section to act as an introduction
The quiz is only 3 questions, one for each setting. The section has users create a least-permission PAT and attempt to push it to GitHub to test out the secret scanning setting. Any thoughts on if I should add a question pertaining to that? It could add some value to the quiz, but isn't really the focus of the section.
=> Added quiz about GitHub security settings

docs/1-introduction/1.3.4-passwords-and-keys.md, docs/1-introduction/1.3.5-networking.md
Fixed the brew cask install command to brew install <> --cask to work on Mac OS. Also fixed the formatting in 1.3.5 where the knowledge check occurred before the final teaching.
=> 1.3.4 - fixed brew --cask && 1.3.5 fixed quiz formatting

docs/3-virtual-machines-containers/3.2-local-development.md
The template from 3.1 uses a Debian iso in its Packer config files.  Updated instructions from this section's exercise to have matching OS.
=> Update base box OS to match template created in section 3.1

docs/3-virtual-machines-containers/3.1-golden-images.md
Previous version of repo (1.0.8) requested missing resources during build.  Switching to v1.0.11 fixes this.
=> Update tag for packer-plugin-vmware repo to latest

docs/3-virtual-machines-containers/3.2-local-development.md
updates exercise instructions to  include a step to add a post-processor to upload box to cloud account, and a hint for installing vagrant-vmware-desktop.
=> update to instructions for local development exercise

docs/4-cloud-computing/4.1.1-aws.md
This section previously instructed the user to manually install the CLI, but this can be done with Brew.  Also, added a note about which version of the AWS CLI to install.
=> Update AWS CLI instructions to use Brew. 

docs/4-cloud-computing/4.1.1-aws.md
Removed references to working with aws-vault in relation to using the AWS CLI.  Replaced steps 3-5 with a document written by Densell Peters describing how to get set up with SSO on the AWS CLI.
=> Remove references to aws-vault

docs/4-cloud-computing/4.2.6-ecs.md, docs/6-release-management/6.3.1-docker.md, docs/6-release-management/6.3.2-helm.md
This pull request primarily updates the repository links in the documentation files across three different sections. The old links to the DevOps Knowledge Share UI and API repositories have been replaced with the new ones.
Here are the key changes:
* [`docs/4-cloud-computing/4.2.6-ecs.md`](diffhunk://#diff-a94cd3cd964c5d21204a46124a5bcb796c1e00c511ca21f5d8876e300f03d818L31-R31): Updated the links to the DevOps Knowledge Share UI and API repositories in the exercise section.
* [`docs/6-release-management/6.3.1-docker.md`](diffhunk://#diff-00d46c520ea94595391ba39303c9cb2ed1be8e9bcdc5145e900c4e34e8092827L27-R27): Changed the links to the DevOps Knowledge Share UI and API repositories in the instructions for creating Dockerhub repositories.
* …
=> docs: updating all dks links to upstream repo

docs/6-release-management/6.2.2-maven-integration.md
Some steps from the first exercise in 6.2.2 were ambiguous, so they have been fleshed out for easier readability.  Fixed some typos and grammatical issues throughout.
=> feat: Update 6.2.2 for clarity and remove typos

docs/7-infrastructure-configuration-management/7.2-ansible.md
Fixed a simple typo where 'has' forgot the h.
=> fix: as to has typo

docs/7-infrastructure-configuration-management/7.2-ansible.md
Currently, the link for learning about self hosted runners uses the same URL as the one above it for Ansible handlers.
=> Updated link for exercise 2, resolves #516

docs/7-infrastructure-configuration-management/7.1.4-terraform-providers.md
The previous link to the devops api pointed to a nonexistent branch that could not be accessed.
=> updated link to devops api

docs/8-kubernetes-container-orchestration/8.4-rbac.md
Typo in step 5 of exercise 1 in chapter 8.4. It was previously "Scores Scoped to Jenkins" and is now "Stores Scoped to Jenkins".
=> Fixed typo in exercise 1 of 8.4

docs/8-kubernetes-container-orchestration/8.4-rbac.md
In the first exercise for section 8.4, using the previously advised version for the Jenkins Helm chart would lead to issues with the Jenkins pod crashing.  Updating to a later version fixed this issue.  
This PR updates the exercise to recommend the latest known working version and adds a tip to check the Jenkins chart version if issues are experienced with the Jenkins pod.
=> feat: Update version of Jenkins Helm chart and add tip about versions

docs/8-kubernetes-container-orchestration/8.7-hello-k8s.md
The Hello K8s project instructions recommend using JIRA for project management, which is no longer recommended to Apprentices.  This PR updates those instructions to recommend GitHub projects instead.
=> feat: Replace JIRA recommendation with GitHub Projects recommendation

docs/8-kubernetes-container-orchestration/8.3-probes.md
"Why might you use the same configuration for a startup probe and ~readiness~ liveness probe?
Its best practice to ensure liveness probes use endpoints that indicate true failure
=> fix: incorrect probe in deliverable question

docs/README.md
Adds basic instructions for adding a new section to the Bootcamp and ensuring that it will become visible on the Bootcamp's sidebar menu.
=> Sidebar instructions

docs/8-kubernetes-container-orchestration/8.6.1-validating-admission-policy.md, examples/ch8/validatingadmissionpolicy/tests/test-deployment4.yaml
Fixed a typo in one of the tests for exercise 2 of chapter 8.6.1, and added a hint to promote best practices regarding the use of admission policies across different namespaces in Kubernetes.
=> chore: fixing typo and adding hint in VAP section of ch8

examples/ch8/controllers/deployment.yaml, examples/ch8/controllers/skeleton-controller.go
This pull request introduces a new Kubernetes controller example in the `examples/ch8/controllers` directory. The changes include adding a deployment configuration file and implementing a basic skeleton for the controller in Go.
=> chore: added skeleton controller and deployment to examples

docs/5-software-development-practices/5.5.4-code-coverage.md
Link to instanbul was broken. Fixed the link so that when pressed it will redirect to the correct website.
=> fixed link to instanbul in docs/5-software-development-practices/5.5.4-code-coverage.md

docs/7-infrastructure-configuration-management/7.1.4-terraform-providers.md, docs/README.md
This includes:
- Moving Schemas, Structs, and Types nearer to the top
- Introducing new first exercise to explicitly do Hashicups tutorial before starting on DevOps API
- Minor flow tweaks throughout the rest to make it make sense with the new ordering
No idea if suggesting bootcamp changes is outside the scope of someone still doing the bootcamp, but figured it was worthwhile to offer up my thoughts on how this section could be better/clearer while it was still fresh in my head.
=> fix: rearranged 7.1.4 Terraform Providers

CLAUDE.md, docs/8-infrastructure-configuration-management/8.3-terraform-providers.md, docs/README.md, docs/_sidebar.md
- Reorganize terraform providers from subsection 8.1.4 to section 8.3
- Update sidebar navigation to reflect new structure
- Update front-matter metadata in README.md for new file path
- Add CLAUDE.md with project development guidance
=> docs: move terraform providers section to top-level 8.3
